workflows:

  lmath-ios-workflow:
    name: LMath iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      vars:
        PROJECT_NAME: LMath

    scripts:
     
    
    artifacts:
      - build/ios/ipa/*.ipa        # ملفات IPA التي سيتم تنزيلها بعد البناء

    publishing:
      # إذا أردت رفع IPA مباشرة إلى TestFlight أو تخزين آخر يمكن إضافته هنا
      # نتركه فارغ لتجربة تنزيل IPA فقط