workflows:

  lmath-ios-workflow:
    name: LMath iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      vars:
        PROJECT_NAME: LMath

    scripts:
      # تثبيت dependencies
      - name: Flutter pub get
        script: |
          flutter pub get

      # تجهيز ملفات iOS
      - name: Prepare iOS
        script: |
          flutter create .

      # توليد Podfile إذا لم يكن موجود
      - name: Generate Podfile
        script: |
          cd ios
          if [ ! -f Podfile ]; then
            pod init
          fi

      # تثبيت CocoaPods
      - name: Install pods
        script: |
          cd ios
          pod install --repo-update

      # بناء التطبيق مع التوقيع (مطلوب Apple Developer Account)
      - name: Build iOS
        script: |
          flutter build ios --release

    # تحديد ملفات الـ artifacts
    artifacts:
      - build/ios/ipa/*.ipa

    # تمكين الـ Build التلقائي على push للفرع main
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true